spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.SpringPhysicalNamingStrategy
springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  writer-with-default-pretty-printer: true
  cache:
    enabled: false
  swagger-ui:
    displayRequestDuration: true
server:
  servlet:
    context-path: /api
  shutdown: graceful
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - loggers
      base-path: /api/actuator
---
spring:
  profiles: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./spring-boot-h2-db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: postgres
    password: postgres
  jpa:
    database: h2
    defer-datasource-initialization: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  devtools:
    restart:
      exclude:
        - src/main/resources/static/**
        - build/**
